Import("env")

# Build protobuf files
proto_sources = [
    "protobuf/application.proto",
    "protobuf/desktop.proto",
    "protobuf/flipper.proto",
    "protobuf/gpio.proto",
    "protobuf/gui.proto",
    "protobuf/property.proto",
    "protobuf/storage.proto",
    "protobuf/system.proto",
]

# Build protobuf C files
compiled_dir = env.ProtoBuilder(
    "compiled",
    proto_sources,
)

# Return the compiled directory for linking
Return("compiled")
